import { useSession } from 'next-auth/react'
import Head from 'next/head'
import React from 'react'
import Header from '../Header'
import Sidebar from '../Sidebar'
import { RootLayoutContainer } from '../StyledComponents/RootLayout.styled'

const RootLayout = ({children}) => {

  const {data: session} = useSession()
  if(!session) return <>bad request</>
  
  return (
    <RootLayoutContainer>
        <Head>
          <title>Foodifyy</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header/>
        <main className='max-w-[1200px] m-auto flex mt-1' >
            <Sidebar/>
            <div className='children md:w-[60%]' >
              {children}
            </div>
        </main>
    </RootLayoutContainer>
  )
}

export default RootLayout